// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentCourse_Many_To_Many.DataAccess;

namespace StudentCourse_Many_To_Many.Migrations
{
    [DbContext(typeof(ManyToManyContext))]
    partial class ManyToManyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.Property<string>("CoursesCourseCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentsStudentNum")
                        .HasColumnType("INTEGER");

                    b.HasKey("CoursesCourseCode", "StudentsStudentNum");

                    b.HasIndex("StudentsStudentNum");

                    b.ToTable("CourseStudent");
                });

            modelBuilder.Entity("StudentCourse_Many_To_Many.Models.Course", b =>
                {
                    b.Property<string>("CourseCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("TEXT");

                    b.Property<int>("ECTS")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Semester")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseCode");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("StudentCourse_Many_To_Many.Models.Student", b =>
                {
                    b.Property<int>("StudentNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentNum");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.HasOne("StudentCourse_Many_To_Many.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesCourseCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentCourse_Many_To_Many.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsStudentNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
